USE ASIATICAS_DB

DROP TRIGGER IF EXISTS trg_q12;
DELIMITER $$
    CREATE TRIGGER trg_q12 BEFORE INSERT ON CLIENTES
    FOR EACH ROW
    BEGIN
        IF NEW.datanascimento > NOW() THEN
            SIGNAL SQLSTATE '88888' SET MESSAGE_TEXT = 'Custom error';
        END IF;
    END$$
DELIMITER ;