USE ASIATICAS_DB

DROP TRIGGER IF EXISTS trg_q13;
DELIMITER $$
CREATE TRIGGER trg_q13 BEFORE DELETE ON FORNECEDORES
FOR EACH ROW
BEGIN
    SIGNAL SQLSTATE '12345' SET MESSAGE_TEXT = "Nem rola, bb";
END$$
DELIMITER ;