USE ASIATICAS_DB

DROP TRIGGER IF EXISTS trg_q2;
DELIMITER $$
CREATE TRIGGER trg_q2 AFTER DELETE ON ITEMVENDAS
FOR EACH ROW
BEGIN
    UPDATE PRODUTOS SET quantidade = quantidade + OLD.quantidade;
END$$
DELIMITER ;

-- DELETE FROM ITEMVENDAS WHERE codvenda=1234567;