USE ASIATICAS_DB

DROP TRIGGER IF EXISTS trg_q4;
DELIMITER $$
CREATE TRIGGER trg_q4 AFTER INSERT ON VENDAS
FOR EACH ROW
BEGIN
    UPDATE CLIENTES SET num_compras = num_compras + 1 WHERE codigo=NEW.codcliente;
END $$
DELIMITER ;