USE ASIATICAS_DB

DROP TRIGGER IF EXISTS trg_q5;
DELIMITER $$
CREATE TRIGGER trg_q5 AFTER DELETE ON VENDAS
FOR EACH ROW
BEGIN
    UPDATE CLIENTES SET num_compras = num_compras - 1 WHERE codigo = OLD.codcliente;
END$$
DELIMITER ;